import Kobon.UpperOpenMathFiveCoreComponents
import Kobon.UpperOpenMathPaidCurvatureBound
import Kobon.UpperOpenMathMixedCurvatureBound
import Kobon.UpperOpenMathMixedFiveCoreComponents
import Kobon.UpperOpenMathHalfCurvatureGain
import Kobon.UpperOpenMathClosedHalfCurvature
import Kobon.UpperOpenMathSingleSourceComponents
import Kobon.UpperOpenMathClosedDoubleRecipientCurvature
import Kobon.UpperOpenMathN13Curvature
import Kobon.UpperOpenMathPartialHalfCurvature
import Kobon.UpperOpenMathClosedN12Curvature
import Kobon.UpperOpenMathPositiveProfileComponents
import Kobon.UpperOpenMathAntipodalThreeNeighbors
import Kobon.UpperOpenMathOneCapActualData
import Kobon.UpperOpenMathMixedDegreeThree
import Kobon.UpperOpenMathForestBudget
import Kobon.UpperOpenMathOrdinaryGlobalCharge
import Kobon.UpperOpenMathMultiplicity

/-! Compact kernel-axiom audit of the actual upper-branch research endpoints.
The class hypotheses are explicit in the individual arrangement theorems.
This file supplies no mathematical assumptions or replacement interfaces. -/

#print axioms Kobon.UpperOpenMathMarkedCurvatureBound.certificate_unmarked_exception_bound
#print axioms Kobon.UpperOpenMathPaidCurvatureBound.certificate_half_exception_bound
#print axioms Kobon.UpperOpenMathMixedCurvatureBound.certificate_mixed_curvature_component_bound
#print axioms Kobon.UpperOpenMathMixedCurvatureBound.certificate_mixed_doubled_component_bound
#print axioms Kobon.UpperOpenMathFiveCoreComponents.certificate_five_core_component_bound
#print axioms Kobon.UpperOpenMathMixedFiveCoreComponents.certificate_mixed_five_component_bound
#print axioms Kobon.UpperOpenMathMixedFiveCoreComponents.certificate_mixed_five_component_perfect_simple
#print axioms Kobon.UpperOpenMathHalfCurvature.certificate_half_defect_bound
#print axioms Kobon.UpperOpenMathHalfCurvatureGain.certificate_half_gain_defect_bound
#print axioms Kobon.UpperOpenMathClosedHalfCurvature.certificate_hybrid_gain_component_defect
#print axioms Kobon.UpperOpenMathSingleSourceCurvature.certificate_closed_single_source_gain
#print axioms Kobon.UpperOpenMathSingleSourceComponents.certificate_seven_core_single_source
#print axioms Kobon.UpperOpenMathSingleSourceComponents.certificate_adaptive_component_defect
#print axioms Kobon.UpperOpenMathSingleSourceComponents.certificate_seven_component_defect
#print axioms Kobon.UpperOpenMathSingleSourceComponents.adaptive_dominates
#print axioms Kobon.UpperOpenMathDoubleRecipientCurvature.certificate_double_recipient_defect_bound
#print axioms Kobon.UpperOpenMathClosedDoubleRecipientCurvature.certificate_hybrid_double_component_defect
#print axioms Kobon.UpperOpenMathPartialRecipients.certificate_partial_anti_degree_zero
#print axioms Kobon.UpperOpenMathPartialCurvature.certificate_partial_defect_bound
#print axioms Kobon.UpperOpenMathPartialHalfCurvature.certificate_partial_half_defect_bound
#print axioms Kobon.UpperOpenMathClosedPartialCurvature.certificate_hybrid_partial_component_defect
#print axioms Kobon.UpperOpenMathN13ActualNoDouble.certificate_n13_no_two_anti_neighbors
#print axioms Kobon.UpperOpenMathN13Curvature.certificate_no_double_recipients
#print axioms Kobon.UpperOpenMathN13Curvature.certificate_n13_anti_degree_le_one
#print axioms Kobon.UpperOpenMathN13Curvature.certificate_source_free_defect_bound
#print axioms Kobon.UpperOpenMathN13Curvature.certificate_closed_source_free_gain
#print axioms Kobon.UpperOpenMathN13Curvature.certificate_source_free_hybrid_component_defect
#print axioms Kobon.UpperOpenMathN13Degree.unrestricted_score_simplifies
#print axioms Kobon.UpperOpenMathN13Degree.unrestricted_dominates_half_gain
#print axioms Kobon.UpperOpenMathN12Recipient.certificate_n12_anti_degree_le_one
#print axioms Kobon.UpperOpenMathN12Curvature.certificate_n12_recipient_le_one
#print axioms Kobon.UpperOpenMathN12Curvature.certificate_n12_source_free_defect_bound
#print axioms Kobon.UpperOpenMathClosedN12Curvature.certificate_closed_n12_source_free_gain
#print axioms Kobon.UpperOpenMathClosedN12Curvature.certificate_n12_source_free_hybrid_component_defect
#print axioms Kobon.UpperOpenMathClosedN12Curvature.source_free_n12_dominates
#print axioms Kobon.UpperOpenMathPositiveProfileComponents.certificate_positive_profile_cost
#print axioms Kobon.UpperOpenMathPositiveProfileComponents.certificate_positive_profile_component_defect
#print axioms Kobon.UpperOpenMathAntipodalThreeNeighbors.certificate_common_neighbor_card_le_two
#print axioms Kobon.UpperOpenMathMixedDegreeThree.certificate_mixed_degree_three_component_bound
#print axioms Kobon.UpperOpenMathForestBudget.certificate_mixed_forest_weighted_bound
#print axioms Kobon.UpperOpenMathForestBudget.certificate_mixed_forest_bound
#print axioms Kobon.UpperOpenMathForestBudget.certificate_triple_forest_bound
#print axioms Kobon.UpperOpenMathMixedCapBudget.certificate_mixed_weighted_defect
#print axioms Kobon.UpperOpenMathTripleCapBudget.certificate_triple_cap_defect
#print axioms Kobon.UpperOpenMathRayResources.certificate_ray_resource_identity
#print axioms Kobon.UpperOpenMathRayResources.certificate_defect_ray_identity
#print axioms Kobon.UpperOpenMathOrdinaryGlobalCharge.certificate_all_line_parity_budget
#print axioms Kobon.UpperOpenMathOrdinaryGlobalCharge.certificate_triple_even_no_ordinary_core_upper
#print axioms Kobon.UpperOpenMathMultiplicity.certificate_defect_even_with_nonshared
